[toolchain]
# region replace rust toolchain dev
channel = "nightly-2023-08-24"
# endregion replace rust toolchain dev
components = [
  "cargo",
  "clippy",
  "llvm-tools",
  "rust-src",
  "rust-std",
  "rustc",
  "rustc-dev",
  "rustfmt",
]
