[alias]
bless   = "test --test uitest -- -- --bless"
dogfood = "run --bin cargo-marker -- --forward-rust-flags"
uilints = "test -p marker_uilints --test uitest"
uitest  = "test --test uitest"

[profile.dev]
split-debuginfo = "unpacked"
