# This file has to be kept in sync with `rust_bors.yml`
name: Rust

on:
  push:
    # Don't run tests, when only text files were modified
    paths-ignore:
    - 'COPYRIGHT'
    - 'LICENSE-*'
    - '**.md'
    - '**.txt'
    # Bors magic branches, these are covered by `rust_bors`
    branches-ignore:
    - '**.tmp'
    - 'staging'
    - 'trying'
    - 'master'
  pull_request:
    # Don't run tests, when only text files were modified
    paths-ignore:
    - 'COPYRIGHT'
    - 'LICENSE-*'
    - '**.md'
    - '**.txt'

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  RUSTDOCFLAGS: "-Dwarnings"
  RUSTFLAGS: "-Dwarnings"

jobs:
  rust:
    runs-on: windows-latest

    # Setup
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2023-06-01
        components: cargo, clippy, rustfmt
    - run: rustc -vV
  
    # Tests
    - run: cargo test
    - run: cargo clippy
    - run: cargo fmt --check
    - run: cargo doc

  # This task ensures, required packages can be build with a stable toolchain
  # the only package requiring nightly should be `marker_rustc_driver` and
  # optionally `marker_adapter`
  rust-crates-build-stable:
    runs-on: ubuntu-latest

    # Setup
    steps:
    - uses: actions/checkout@v3
    - run: rm rust-toolchain
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: cargo
    - run: rustc -vV

    # Test
    - run: cargo build --package cargo_marker
    - run: cargo build --package marker_api
    - run: cargo build --package marker_utils
    - run: cargo build --package marker_uitest
    - run: cargo build --package marker_uilints
